#!/bin/zsh
ZGEN_LOADED=()
ZGEN_COMPLETIONS=()

zgen oh-my-zsh


# Absolute Theme https://github.com/NelsonBrandao/absolute
zgen load NelsonBrandao/absolute

# If zsh-syntax-highlighting is bundled after zsh-history-substring-search,
# they break, so get the order right.
zgen load zsh-users/zsh-syntax-highlighting
zgen load zsh-users/zsh-history-substring-search

# Set keystrokes for substring searching
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# https://github.com/unixorn/awesome-zsh-plugins
# Add my collection of miscellaneous utility functions.
#zgen load unixorn/jpb.zshplugin

# Warn you when you run a command that you've set an alias for
zgen load djui/alias-tips

# Add my collection of git helper scripts
#zgen load unixorn/git-extra-commands

# A collection of scripts that might be useful to sysadmins
#zgen load skx/sysadmin-util

# Adds aliases to open your current repo & branch on github.
zgen load peterhurford/git-it-on.zsh

# Tom Limoncelli's tooling for storing private information (keys, etc)
# in a repository securely by encrypting them with gnupg
zgen load StackExchange/blackbox

# Load some oh-my-zsh plugins
zgen oh-my-zsh plugins/pip
zgen oh-my-zsh plugins/sudo
zgen oh-my-zsh plugins/colored-man-pages
zgen oh-my-zsh plugins/git
zgen oh-my-zsh plugins/github
zgen oh-my-zsh plugins/python
zgen oh-my-zsh plugins/rsync
# zgen oh-my-zsh plugins/vagrant

# A set of shell functions to make it easy to install small apps and
# utilities distributed with pip.
zgen load sharat87/pip-app

zgen load chrissicool/zsh-256color

# Load more completion files for zsh from the zsh-lovers github repo
zgen load zsh-users/zsh-completions src

# Docker completion
# zgen load srijanshetty/docker-zsh

# Load me last
GENCOMPL_FPATH=$HOME/.zsh/complete

# Add Fish-like autosuggestions to your ZSH
zgen load zsh-users/zsh-autosuggestions

# k is a zsh script / plugin to make directory listings more readable,
# adding a bit of color and some git status information on files and directories
zgen load supercrabtree/k

# # Bullet train prompt setup
# zgen load caiogondim/bullet-train-oh-my-zsh-theme bullet-train

# Save it all to init script
zgen save
